# Server Configuration
server:
  port: 9500

spring:

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/patterns
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true