# Server Configuration
server:
  port: 9501

spring:

  # Database Configuration
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:lambda
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092